In [1]:
import os, time
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers.experimental import preprocessing
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import BatchNormalization
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([[1]])
y = np.array([10])

print(X.shape)

(1, 1)


In [3]:
tf.keras.backend.clear_session()

init = tf.constant_initializer(np.array([1]))


layerIn = Input(shape=(1,))
layerMid = Dense(1, kernel_initializer=tf.constant_initializer(np.array([[1]])), activation='sigmoid')(layerIn)
layerMid = Dense(2, kernel_initializer=tf.constant_initializer(np.array([[2,3]])), activation='sigmoid')(layerMid)
layerOut = Dense(1, kernel_initializer=tf.constant_initializer(np.array([[4],[5]])))(layerMid)
model = Model(inputs=layerIn, outputs=layerOut)

In [4]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 2         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 4         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(1, 2) dtype=float32, numpy=array([[2., 3.]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[4.],
        [5.]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [6]:
y_pred = model(X).numpy()
print(y_pred)

[[7.7456007]]


In [7]:
model.compile(
        optimizer=tf.optimizers.Adam(learning_rate=0.1),
        loss='mean_absolute_error', metrics=['mean_absolute_percentage_error'])


In [8]:
history = model.fit(X,y, epochs=1)

1/1 [==============================] - 0s 2ms/step - loss: 2.2544 - mean_absolute_percentage_error: 22.5440


In [9]:
model.trainable_weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.0999994]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.09999938], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(1, 2) dtype=float32, numpy=array([[2.0999992, 3.099999 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0.09999948, 0.09999929], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[4.0999994],
        [5.0999994]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.09999968], dtype=float32)>]

In [10]:
y_pred = model(X).numpy()
print(y_pred)

[[8.280891]]


In [11]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [12]:
phi_h = sigmoid(1)
print(phi_h)

0.7310585786300049


In [13]:
z_h_1 = phi_h*2
z_h_2 = phi_h*3

In [14]:
phi_out_1 = sigmoid(z_h_1)
phi_out_2 = sigmoid(z_h_2)
print(phi_out_1, phi_out_2)

0.8118562749129378 0.899635013659718


In [15]:
y_hat = phi_out_1*4 + phi_out_2*5
print(y_hat)

7.745600167950341


In [16]:
tf.keras.metrics.mean_squared_error(
    y, y_hat
)

<tf.Tensor: shape=(), dtype=float64, numpy=5.08231860274553>

In [22]:
np.power(y_hat-y,2)

array([5.0823186])

array([10])